Clean up code to make it shellchecker check passing
Note: we ignore "SC2317" so we do not get a warning for the __DATA__ block

diff --git a/zabbix-dump b/zabbix-dump
--- a/zabbix-dump
+++ b/zabbix-dump
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+# shellcheck disable=SC2317 # so __DATA__ block doesn't get flagged
 VERSION=0.9.12
 #
 # NAME
@@ -324,27 +325,28 @@ DB_OPTS=()
 case $DBTYPE in
     mysql)
         [ -n "$MYSQL_CONFIG" ] && DB_OPTS=("${DB_OPTS[@]}" --defaults-extra-file="$MYSQL_CONFIG")
-        [ -n "$DBSOCKET" ] && DB_OPTS=("${DB_OPTS[@]}" -S $DBSOCKET)
-        [ -n "$DBHOST" ] && DB_OPTS=("${DB_OPTS[@]}" -h $DBHOST)
-        [ -n "$DBUSER" ] && DB_OPTS=("${DB_OPTS[@]}" -u $DBUSER)
+        [ -n "$DBSOCKET" ] && DB_OPTS=("${DB_OPTS[@]}" -S "$DBSOCKET")
+        [ -n "$DBHOST" ] && DB_OPTS=("${DB_OPTS[@]}" -h "$DBHOST")
+        [ -n "$DBUSER" ] && DB_OPTS=("${DB_OPTS[@]}" -u "$DBUSER")
         [ -n "$DBPASS" ] && DB_OPTS=("${DB_OPTS[@]}" -p"$DBPASS")
         DB_OPTS=("${DB_OPTS[@]}" -P"$DBPORT")
         DB_OPTS_BATCH=("${DB_OPTS[@]}" --batch --silent)
-        [ -n "$DBNAME" ] && DB_OPTS_BATCH=("${DB_OPTS_BATCH[@]}" -D $DBNAME)
+        [ -n "$DBNAME" ] && DB_OPTS_BATCH=("${DB_OPTS_BATCH[@]}" -D "$DBNAME")
         [ "${COLUMN_NAMES}" == "yes" ] && DB_OPTS=("${DB_OPTS[@]}" --complete-insert --quote-names)
         ;;
     psql)
-        [ -n "$DBSOCKET" ] && DB_OPTS=("${DB_OPTS[@]}" -h $DBSOCKET)
-        [ -n "$DBHOST" ] && DB_OPTS=("${DB_OPTS[@]}" -h $DBHOST)
-        [ -n "$DBUSER" ] && DB_OPTS=("${DB_OPTS[@]}" -U $DBUSER)
+        [ -n "$DBSOCKET" ] && DB_OPTS=("${DB_OPTS[@]}" -h "$DBSOCKET")
+        [ -n "$DBHOST" ] && DB_OPTS=("${DB_OPTS[@]}" -h "$DBHOST")
+        [ -n "$DBUSER" ] && DB_OPTS=("${DB_OPTS[@]}" -U "$DBUSER")
         DB_OPTS=("${DB_OPTS[@]}" -p"$DBPORT")
         if [ -n "$DBPASS" ]; then
-            export PGPASSFILE=$(mktemp -u)
-            echo "$DBHOST:$DBPORT:$DBNAME:$DBUSER:$DBPASS" > $PGPASSFILE
-            chmod 600 $PGPASSFILE
+            PGPASSFILE=$(mktemp -u)
+            export PGPASSFILE
+            echo "$DBHOST:$DBPORT:$DBNAME:$DBUSER:$DBPASS" > "$PGPASSFILE"
+            chmod 600 "$PGPASSFILE"
         fi
         DB_OPTS_BATCH=("${DB_OPTS[@]}" -AtwX)
-        [ -n "$DBNAME" ] && DB_OPTS_BATCH=("${DB_OPTS_BATCH[@]}" -d $DBNAME)
+        [ -n "$DBNAME" ] && DB_OPTS_BATCH=("${DB_OPTS_BATCH[@]}" -d "$DBNAME")
         [ "${CUSTOM_FORMAT}" == "yes" ] && DB_OPTS=("${DB_OPTS[@]}" --format=custom)
         [ "${CUSTOM_FORMAT}" == "no" ] && DB_OPTS=("${DB_OPTS[@]}" --format=plain)
         [ "${COLUMN_NAMES}" == "yes" ] && DB_OPTS=("${DB_OPTS[@]}" --inserts --column-inserts --quote-all-identifiers)
@@ -398,7 +400,7 @@ elementIn () {
     return 1
 }
 check_binary() {
-    if ! which $1 > /dev/null; then
+    if ! which "$1" > /dev/null; then
         echo "Executable '$1' not found." >&2
         case $1 in
             mysql)
@@ -410,8 +412,8 @@ check_binary() {
     fi
 }
 clean_psql_pass() {
-    if [ $DBTYPE = "psql" -a -n "$PGPASSFILE" ]; then
-        rm -f $PGPASSFILE
+    if [ "$DBTYPE" = "psql" ] && [ -n "$PGPASSFILE" ]; then
+        rm -f "$PGPASSFILE"
     fi
 }
 
@@ -438,8 +440,8 @@ KNOWN_TABLES=()
 while read -r line; do
     table=$(echo "$line" | cut -d" " -f1)
     echo "$line" | cut -d" " -f5 | grep -qi "SCHEMAONLY"
-    test $? -eq 0 && SCHEMAONLY_TABLES+=($table)
-    KNOWN_TABLES+=($table)
+    test $? -eq 0 && SCHEMAONLY_TABLES+=("$table")
+    KNOWN_TABLES+=("$table")
 done < <(sed '0,/^__DATA__$/d' "${BASH_SOURCE[*]}" | tr -s " ")
 
 # paranoid check
@@ -455,26 +457,27 @@ fi
 [ "$QUIET" == "no" ] && echo "Fetching list of existing tables..."
 case $DBTYPE in
     mysql)
-        DB_TABLES=$(mysql "${DB_OPTS_BATCH[@]}" -e "SELECT table_name FROM information_schema.tables WHERE table_schema = '$DBNAME'" 2>$ERRORLOG)
+        DB_TABLES=$(mysql "${DB_OPTS_BATCH[@]}" -e "SELECT table_name FROM information_schema.tables WHERE table_schema = '$DBNAME'" 2>"$ERRORLOG")
         ;;
     psql)
-        DB_TABLES=$(psql "${DB_OPTS_BATCH[@]}" -c "SELECT table_name FROM information_schema.tables WHERE table_schema='$DBSCHEMA' AND table_catalog='$DBNAME' AND table_type='BASE TABLE'" 2>$ERRORLOG)
+        DB_TABLES=$(psql "${DB_OPTS_BATCH[@]}" -c "SELECT table_name FROM information_schema.tables WHERE table_schema='$DBSCHEMA' AND table_catalog='$DBNAME' AND table_type='BASE TABLE'" 2>"$ERRORLOG")
         ;;
 esac
+# shellcheck disable=SC2181
 if [ $? -ne 0 ]; then
     echo "ERROR while trying to access database:" 2>&1;
-    cat $ERRORLOG 2>&1;
+    cat "$ERRORLOG" 2>&1;
     clean_psql_pass
     exit 1;
 fi
 
 DB_TABLES=$(echo "$DB_TABLES" | sort)
-DB_TABLE_NUM=$(echo "$DB_TABLES" | wc -l)
+# DB_TABLE_NUM=$(echo "$DB_TABLES" | wc -l)
 
 # Check if existing tables are known
 UNKNOWN_TABLES=()
 while read -r table; do
-    elementIn "$table" "${KNOWN_TABLES[@]}" || UNKNOWN_TABLES+=($table)
+    elementIn "$table" "${KNOWN_TABLES[@]}" || UNKNOWN_TABLES+=("$table")
 done <<<"$DB_TABLES"
 if [ ${#UNKNOWN_TABLES[@]} -gt 0 ]; then
     if [[ "$QUIET" == "no" || $HANDLE_UNKNOWN == "fail" ]]; then
@@ -503,6 +506,7 @@ case $DBTYPE in
         DB_VER=$(psql "${DB_OPTS_BATCH[@]}" -c "select optional from dbversion;" 2>/dev/null)
         ;;
 esac
+# shellcheck disable=SC2181
 if [ $? -eq 0 ]; then
     # version string is like: 02030015
     re='(.*)([0-9]{2})([0-9]{4})'
@@ -517,7 +521,6 @@ DUMPFILEBASE="${DUMPFILENAME_PREFIX}_$(date +%Y%m%d-%H%M)${VERSION}.sql"
 DUMPFILE="$DUMPDIR/$DUMPFILEBASE"
 
 PROCESSED_SCHEMAONLY_TABLES=()
-i=0
 
 # make folder if not std out
 [ "$DUMPDIR" != "-" ] && mkdir -p "${DUMPDIR}"
@@ -530,73 +533,81 @@ case $DBTYPE in
         if [ $HANDLE_UNKNOWN == "ignore" ]; then
             while read -r table; do
                 if elementIn "$table" "${UNKNOWN_TABLES[@]}"; then
-                    DUMP_OPTS+=(--ignore-table=$DBNAME.$table)
+                    DUMP_OPTS+=(--ignore-table="$DBNAME.$table")
                 fi
             done <<<"$DB_TABLES"
         fi
 
         if [ "$DUMPDIR" != "-" ]; then
-            mysqldump "${DB_OPTS[@]}" "${DUMP_OPTS[@]}" $DBNAME > "$DUMPFILE" 2>$ERRORLOG
+            mysqldump "${DB_OPTS[@]}" "${DUMP_OPTS[@]}" "$DBNAME" > "$DUMPFILE" 2>"$ERRORLOG"
         else
-            mysqldump "${DB_OPTS[@]}" "${DUMP_OPTS[@]}" $DBNAME 2>$ERRORLOG
+            mysqldump "${DB_OPTS[@]}" "${DUMP_OPTS[@]}" "$DBNAME" 2>"$ERRORLOG"
         fi;
-
-        if [ $? -ne 0 ]; then echo $'\nERROR: Could not backup table schemas.\n' >&2; cat $ERRORLOG >&2; exit 1; fi
+        # shellcheck disable=SC2181
+        if [ $? -ne 0 ]; then
+            echo $'\nERROR: Could not backup table schemas.\n' >&2;
+            cat "$ERRORLOG" >&2;
+            exit 1;
+        fi
 
         # dump data
         DUMP_OPTS=(--opt --single-transaction --skip-lock-tables --no-create-info --skip-extended-insert --skip-triggers)
         while read -r table; do
             if elementIn "$table" "${SCHEMAONLY_TABLES[@]}"; then
-                DUMP_OPTS+=(--ignore-table=$DBNAME.$table)
-                PROCESSED_SCHEMAONLY_TABLES+=($table)
+                DUMP_OPTS+=(--ignore-table="$DBNAME.$table")
+                PROCESSED_SCHEMAONLY_TABLES+=("$table")
             fi
             if [ $HANDLE_UNKNOWN == "ignore" ]; then
                 if elementIn "$table" "${UNKNOWN_TABLES[@]}"; then
-                    DUMP_OPTS+=(--ignore-table=$DBNAME.$table)
+                    DUMP_OPTS+=(--ignore-table="$DBNAME.$table")
                 fi
             fi
         done <<<"$DB_TABLES"
 
         if [ "$DUMPDIR" != "-" ]; then
-            mysqldump "${DB_OPTS[@]}" "${DUMP_OPTS[@]}" $DBNAME >> "$DUMPFILE" 2>$ERRORLOG
+            mysqldump "${DB_OPTS[@]}" "${DUMP_OPTS[@]}" "$DBNAME" >> "$DUMPFILE" 2>"$ERRORLOG"
         else
-            mysqldump "${DB_OPTS[@]}" "${DUMP_OPTS[@]}" $DBNAME 2>$ERRORLOG
+            mysqldump "${DB_OPTS[@]}" "${DUMP_OPTS[@]}" "$DBNAME" 2>"$ERRORLOG"
         fi;
-
-        if [ $? -ne 0 ]; then echo $'\nERROR: Could not backup table data.\n' >&2; cat $ERRORLOG >&2; exit 1; fi
+        # shellcheck disable=SC2181
+        if [ $? -ne 0 ];
+            then echo $'\nERROR: Could not backup table data.\n' >&2;
+            cat "$ERRORLOG" >&2;
+            exit 1;
+        fi
     ;;
     psql)
         DUMP_OPTS=()
         while read -r table; do
             if [ $HANDLE_UNKNOWN == "ignore" ]; then
                 if elementIn "$table" "${UNKNOWN_TABLES[@]}"; then
-                    DUMP_OPTS+=(--exclude-table=$table)
+                    DUMP_OPTS+=(--exclude-table="$table")
                 fi
             fi
             if elementIn "$table" "${SCHEMAONLY_TABLES[@]}"; then
-                DUMP_OPTS+=(--exclude-table-data=$table)
-                PROCESSED_SCHEMAONLY_TABLES+=($table)
+                DUMP_OPTS+=(--exclude-table-data="$table")
+                PROCESSED_SCHEMAONLY_TABLES+=("$table")
             fi
         done <<<"$DB_TABLES"
 
-        [ -n "$DBSCHEMA" ] && DUMP_OPTS=("${DUMP_OPTS[@]}" -n $DBSCHEMA)
+        [ -n "$DBSCHEMA" ] && DUMP_OPTS=("${DUMP_OPTS[@]}" -n "$DBSCHEMA")
 
         if [ "$DUMPDIR" != "-" ]; then
-            pg_dump "${DB_OPTS[@]}" "${DUMP_OPTS[@]}" -d $DBNAME > "$DUMPFILE" 2>$ERRORLOG
+            pg_dump "${DB_OPTS[@]}" "${DUMP_OPTS[@]}" -d "$DBNAME" > "$DUMPFILE" 2>"$ERRORLOG"
         else
-            pg_dump "${DB_OPTS[@]}" "${DUMP_OPTS[@]}" -d $DBNAME 2>$ERRORLOG
+            pg_dump "${DB_OPTS[@]}" "${DUMP_OPTS[@]}" -d "$DBNAME" 2>"$ERRORLOG"
         fi;
-
+        # shellcheck disable=SC2181
         if [ $? -ne 0 ]; then
             echo $'\nERROR: Could not backup database.\n' >&2
-            cat $ERRORLOG >&2
+            cat "$ERRORLOG" >&2
             clean_psql_pass
             exit 1
         fi
     ;;
 esac
 
-rm $ERRORLOG
+rm "$ERRORLOG"
 
 #
 # COMPRESS BACKUP
@@ -622,11 +633,13 @@ fi
 #
 # ROTATE OLD BACKUPS
 #
-if [ $GENERATIONSTOKEEP -gt 0 ] && [ "$DUMPDIR" != "-" ]; then
+if [ "$GENERATIONSTOKEEP" -gt 0 ] && [ "$DUMPDIR" != "-" ]; then
     [ "$QUIET" == "no" ] && echo "Removing old backups, keeping up to $GENERATIONSTOKEEP"
-    REMOVE_OLD_CMD="cd \"$DUMPDIR\" && ls -t \"${DUMPFILENAME_PREFIX}\"* | /usr/bin/awk \"NR>${GENERATIONSTOKEEP}\" | xargs rm -f "
-    eval ${REMOVE_OLD_CMD}
-    if [ $? -ne 0 ]; then
+    REMOVE_OLD_CMD="cd \"$DUMPDIR\" &&
+    ls -t \"${DUMPFILENAME_PREFIX}\"* |
+    /usr/bin/awk \"NR>${GENERATIONSTOKEEP}\" |
+    xargs rm -f "
+    if ! eval "${REMOVE_OLD_CMD}"; then
         echo "ERROR: Could not rotate old backups" >&2
         clean_psql_pass
         exit 1
